/**
 * Payload shape for Socket.IO `event` on namespace `/events`.
 * @see frontend-realtime-events.md
 */
export type DomainEventMessage = {
  type: string;
} & Record<string, unknown>;

export const DOMAIN_EVENT_TYPES = [
  "BOOKING_CREATED",
  "BOOKING_CONFIRMED",
  "BOOKING_IN_PROGRESS",
  "BOOKING_COMPLETED",
  "BOOKING_EXPIRED",
  "BOOKING_CANCELLED",
  "BOOKING_DECLINED",
  "BOOKING_COUNTERED",
  "KRAFTER_SELECTED",
  "BOOKING_REOPENED_FOR_RECOMMENDATIONS",
  "BOOKING_PUBLISHED_TO_MARKETPLACE",
  "BOOKING_DRAFT_DELETED",
  "ARTISAN_APPLIED",
  "MARKETPLACE_APPLICATION_REJECTED",
  "PAYMENT_PENDING",
  "PAYMENT_RELEASED",
  "PAYMENT_REFUNDED",
  "PAYMENT_SPLIT",
  "PAYMENT_INITIATED",
  "PAYMENT_DISPUTED",
  "PAYMENT_ESCROWED",
  "PAYMENT_AUTHORIZED",
  "ARTISAN_WALLET_WITHDRAWN",
  "ARTISAN_WALLET_WITHDRAWAL_FAILED",
  "ARTISAN_STRIPE_CONNECTED",
  "ARTISAN_STRIPE_ONBOARDING_COMPLETED",
  "ARTISAN_BANK_PAYOUT_PAID",
  "ARTISAN_BANK_PAYOUT_FAILED",
  "DISPUTE_OPENED",
  "DISPUTE_UNDER_REVIEW",
  "DISPUTE_RESOLVED",
  "ARTISAN_VERIFIED",
  "PROFILE_UPDATED",
  "CUSTOM_KRAFT_PUBLISHED",
  "CUSTOM_KRAFT_EXPIRED",
  "CUSTOM_KRAFT_CANCELLED",
] as const;

export type DomainEventType = (typeof DOMAIN_EVENT_TYPES)[number];
